<!-- Intended as an attached component to any input box that has character count rules (eg. minimum character count, maximum character count) -->
<!-- Consider just attaching the actual input box within this component, with variables for custom modification. -->
<!-- NOT ACTIVELY USED, CHECK IF EVEN NEEDED -->

<!-- WORK IN PROGRESS. Most code here is generated by CoPilot and requires testing / modification. -->

<template>
    <div class="character-counter">
        <p class="character-counter-text">{{ characterCount }} / {{ maxCharacters }}</p>
    </div>
</template>

<script>
    export default {
        name: "CharacterCounter",
        props: {
            characterCount: {
                type: Number,
                required: true
            },
            maxCharacters: {
                type: Number,
                required: true
            }
        }
    }
</script>

<style scoped>
    .character-counter {
        display: flex;
        justify-content: flex-end;
    }

    .character-counter-text {
        font-size: 0.8rem;
        color: #6c757d;
    }
</style>